lang: en
debug: true
clans:
  confirm-limit: 10.0
  clan-list-max-pages: 7
  member-limit: -1
  cost: 10000
  initial-balance: 1000
  data:
    type: "json"
    json:
      file: "clans"
    yaml:
      file: "clans"
notifications:
  # in minutes
  # -1 to disable
  # Default: 1 week = 10080 minutes
  keep-for: 10080
  file: "notifications"